title: Palette Printer
email: your-email@example.com

description: >-
  A sass tool that takes all the effort out of supporting multiple color schemes on your website.

baseurl: "/palette-printer"
url: "https://opsaaaaa.github.io/"
